name: Security Scan

on: [push, pull_request]

jobs:
  dependency-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: 'pip' # Cache pip dependencies

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Cache Dependency-Check Data
        uses: actions/cache@v3
        with:
          path: ~/.dependency-check/data
          key: ${{ runner.os }}-dependency-check-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-dependency-check-

      - name: Download Dependency-Check
        run: |
          wget -q https://github.com/dependency-check/DependencyCheck/releases/download/v9.0.9/dependency-check-9.0.9-release.zip
          unzip -q dependency-check-9.0.9-release.zip

      - name: Run Dependency-Check
        run: |
          ./dependency-check/bin/dependency-check.sh --scan . \
            --format HTML \
            --project "Python-GitHub-Action" \
            --out . \
            --nvdApiKey "4651c208-aef6-4b4c-807a-58fae9335853" \
            --nvdApiDelay 6000 \
            --failOnCVSS 7 # Optional: Fail build on high vulnerabilities

      - name: Upload HTML report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: dependency-check-report.html