name: OWASP Dependency Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  dependency-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
  
      - name: Set up Java
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-17-jdk
          echo "JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64" >> $GITHUB_ENV
          
      - name: Verify Java installation
        run: |
          echo "JAVA_HOME=$JAVA_HOME"
          java -version
          
      - name: Download OWASP Dependency-Check
        run: |
          mkdir -p dependency-check
          cd dependency-check
          wget https://github.com/jeremylong/DependencyCheck/releases/download/v9.0.8/dependency-check-9.0.8-release.zip
          unzip dependency-check-9.0.8-release.zip
          chmod +x dependency-check/bin/dependency-check.sh
          
      - name: Create reports directory
        run: mkdir -p reports
          
      - name: Run OWASP Dependency-Check
        run: |
          cd dependency-check
          ./dependency-check/bin/dependency-check.sh \
            --scan ../ \
            --project "Python-Project" \
            --format "HTML" \
            --format "SARIF" \
            --out ../reports \
            --enableExperimental
        continue-on-error: true
            
      - name: Upload Test results
        uses: actions/upload-artifact@v4
        with:
          name: Dependency Check Report
          path: reports
          
      - name: Upload SARIF report to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: reports/dependency-check-report.sarif
