name: Dependency Check with Cached Database

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  dependency-check:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Dependency-Check DB
        uses: actions/cache@v4
        with:
          path: ${{ runner.temp }}/dc-data
          key: dc-data-${{ runner.os }}-v1

      - name: Run OWASP Dependency-Check
        env:
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
        run: |
          mkdir -p odc-reports
          docker run --rm \
            -e NVD_API_KEY="$NVD_API_KEY" \
            -v "${{ github.workspace }}":/src \
            -v "${{ runner.temp }}/dc-data":/usr/share/dependency-check/data \
            -v "${{ github.workspace }}/odc-reports":/report \
            owasp/dependency-check:latest \
            --project "${{ github.repository }}@${{ github.ref_name }}" \
            --scan /src \
            --out /report \
            --format HTML \
            --enableExperimental \
            --exclude "/src/venv/.*" \
            --exclude "/src/.venv/.*" \
            --failOnCVSS 7

      - name: Upload HTML report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: odc-reports/dependency-check-report.html
          if-no-files-found: error