name: Dependency Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'  # Run weekly

jobs:
  dependency-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Verify Java installation
      run: |
        echo "JAVA_HOME=$JAVA_HOME"
        java -version
        
    - name: Cache Dependency-Check data
      uses: actions/cache@v4
      with:
        path: ~/.dependency-check-data
        key: ${{ runner.os }}-dependency-check-data
      
    - name: Download and run Dependency-Check
      run: |
        # Create directories
        mkdir -p $HOME/dependency-check/data
        mkdir -p $HOME/dependency-check/reports
        
        # Download the latest release
        wget -q https://github.com/jeremylong/DependencyCheck/releases/download/v8.4.2/dependency-check-8.4.2-release.zip
        unzip -q dependency-check-8.4.2-release.zip
        
        # Run the dependency check
        ./dependency-check/bin/dependency-check.sh \
          --project "My Python Project" \
          --scan . \
          --format HTML \
          --format XML \
          --enableExperimental \
          --out $HOME/dependency-check/reports \
          --scan "**/*.py" \
          --scan "requirements.txt" \
          --scan "Pipfile" \
          --scan "Pipfile.lock" \
          --scan "poetry.lock"
      
    - name: Upload Dependency-Check reports
      uses: actions/upload-artifact@v4
      with:
        name: dependency-check-reports
        path: ~/dependency-check/reports/
        
    - name: Check for high severity issues
      run: |
        if grep -q "CVSS score >= 8.0" $HOME/dependency-check/reports/dependency-check-report.html; then
          echo "High severity vulnerabilities found!"
          exit 1
        fi
