name: Dependency Check with Cached Database

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  security-events: write

jobs:
  dependency-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python (for Pip analyzer)
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Cache Dependency-Check data
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository/org/owasp/dependency-check
        key: odc-${{ runner.os }}-${{ hashFiles('**/requirements*.txt', '**/Pipfile.lock') }}
        restore-keys: |
          odc-${{ runner.os }}-

    - name: Run OWASP Dependency-Check (Docker)
      run: |
        mkdir -p reports
        docker run --rm \
          -v "$PWD:/src" \
          -v "$HOME/.m2:/root/.m2" \
          owasp/dependency-check:latest \
          --project "${{ github.repository }}" \
          --scan /src \
          --format "HTML,JSON,SARIF" \
          --out /src/reports \
          --failOnCVSS 7
      # No API key is provided on purpose; first run may be slower due to rate limiting

    - name: Upload SARIF to GitHub Security
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: reports/dependency-check-report.sarif

    - name: Upload full report artifact
      uses: actions/upload-artifact@v4
      with:
        name: dependency-check-report
        path: reports
        run: |
          if grep -q "CVSS score >= 8.0" reports/dependency-check-report.html; then
            echo "High severity vulnerabilities found!"
            exit 1
          fi
