name: Dependency-Check with Thread Pool Fix

on: [push, pull_request]

jobs:
  dependency-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Clear Dependency-Check cache
        run: rm -rf ~/.dependency-check/data

      - name: Download Latest Dependency-Check
        run: |
          wget https://github.com/jeremylong/DependencyCheck/releases/download/v10.0.2/dependency-check-10.0.2-release.zip
          unzip dependency-check-10.0.2-release.zip

      - name: Run Dependency-Check with thread pool fixes
        run: |
          ./dependency-check/bin/dependency-check.sh \
            --scan . \
            --format HTML \
            --project "${{ github.repository }}" \
            --out . \
            --nvdApiKey ${{ secrets.NVD_API_KEY }} \
            --nvdApiDelay 6000 \
        env:
          JAVA_OPTS: "-Xms2g -Xmx4g -Dthread.timeout=300000"

      - name: Upload HTML report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: dependency-check-report.html