name: OWASP Dependency-Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'  # Запуск каждое воскресенье

jobs:
  dependency-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          
      - name: Cache dependency-check data
        uses: actions/cache@v4
        with:
          path: ~/.dependency-check/data
          key: ${{ runner.os }}-dependency-check-data-${{ hashFiles('**/pom.xml', '**/build.gradle', '**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-dependency-check-data-
      
      # Скачиваем и запускаем OWASP Dependency-Check с инициализацией базы данных
      - name: Download and Initialize OWASP Dependency-Check
        run: |
          # Создаем директорию для dependency-check
          mkdir -p $HOME/dependency-check
          
          # Скачиваем релиз
          wget -q https://github.com/jeremylong/DependencyCheck/releases/download/v8.4.0/dependency-check-8.4.0-release.zip -O $HOME/dependency-check.zip
          
          # Распаковываем в созданную директорию
          unzip -q $HOME/dependency-check.zip -d $HOME
          
          # Проверяем, что скрипт существует и делаем его исполняемым
          chmod +x $HOME/dependency-check/bin/dependency-check.sh
          
          # Создаем директорию для базы данных
          mkdir -p ~/.dependency-check/data
          
          # Скачиваем и инициализируем базу данных с помощью команды --updateonly
          $HOME/dependency-check/bin/dependency-check.sh --updateonly
          
      # Запускаем сканирование с флагом --noupdate после того, как база инициализирована
      - name: Run OWASP Dependency-Check Scan
        run: |
          $HOME/dependency-check/bin/dependency-check.sh \
            --project "My Project" \
            --scan . \
            --format "HTML" \
            --out ./reports \
            --noupdate
          
      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: ./reports/dependency-check-report.html
