name: OWASP Dependency-Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  dependency-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          
      - name: Cache dependency-check data
        uses: actions/cache@v4
        with:
          path: ~/.dependency-check
          key: ${{ runner.os }}-dependency-check-${{ hashFiles('**/pom.xml', '**/build.gradle', '**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-dependency-check-
      
      - name: Download OWASP Dependency-Check
        run: |
          mkdir -p ./dependency-check/
          wget -q https://github.com/jeremylong/DependencyCheck/releases/download/v8.4.0/dependency-check-8.4.0-release.zip
          unzip -q dependency-check-8.4.0-release.zip -d ./dependency-check/
          
      - name: Run Dependency-Check
        run: |
          ./dependency-check/bin/dependency-check.sh \
            --project "My Project" \
            --scan . \
            --format HTML \
            --out reports \
            --enableExperimental \
            --suppression suppression.xml
          
      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: reports/dependency-check-report.html
          
      - name: Check for vulnerabilities
        run: |
          if grep -q "<td>High</td>" reports/dependency-check-report.html || grep -q "<td>Critical</td>" reports/dependency-check-report.html; then
            echo "High or Critical vulnerabilities found!"
            exit 1
          fi
