name: Dependency Check with Cached Database

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  dependency-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Cache Dependency-Check DB
      uses: actions/cache@v4
      with:
        path: ./.odc-data
        key: odc-${{ runner.os }}-${{ hashFiles('**/requirements*.txt', '**/Pipfile.lock', '**/poetry.lock') }}
        restore-keys: |
          odc-${{ runner.os }}-

    - name: Run OWASP Dependency-Check (HTML, with NVD key)
      env:
        NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
      run: |
        mkdir -p reports .odc-data
        SAFE_PROJECT="${GITHUB_REPOSITORY//\//-}"  # Romiusse-IS
        docker run --rm \
          -e NVD_API_KEY="$NVD_API_KEY" \
          -v "$PWD:/src" \
          -v "$PWD/.odc-data:/usr/share/dependency-check/data" \
          owasp/dependency-check:latest \
          --project "$SAFE_PROJECT" \
          --scan /src \
          --format HTML \
          --out /src/reports \
          --failOnCVSS 7 \
          --log /src/reports/odc.log

    - name: Upload HTML report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: dependency-check-report
        path: |
          reports/dependency-check-report.html
          reports/odc.log
