name: Dependency-Check Security Scan

on: [push, pull_request]

jobs:
  dependency-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Clear Dependency-Check cache
        run: rm -rf ~/.dependency-check/data

      - name: Download Latest Dependency-Check
        run: |
          wget -q https://github.com/jeremylong/DependencyCheck/releases/download/v10.0.2/dependency-check-10.0.2-release.zip
          unzip -q dependency-check-10.0.2-release.zip

      - name: Run Dependency-Check
        env:
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
        run: |
          # Формируем команду с учетом наличия API ключа
          COMMAND="./dependency-check/bin/dependency-check.sh \
            --scan . \
            --format HTML \
            --project \"${{ github.repository }}\" \
            --out . \
            --nvdApiDelay 6000"
          
          # Добавляем API ключ если он есть
          if [ -n "$NVD_API_KEY" ]; then
            COMMAND="$COMMAND --nvdApiKey $NVD_API_KEY"
          fi
          
          # Выполняем команду
          eval $COMMAND
        env:
          JAVA_TOOL_OPTIONS: "-Xms2g -Xmx4g"

      - name: Upload HTML report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: dependency-check-report.html
