name: OWASP Dependency Check

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  dependency-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: OWASP Dependency Check
        uses: actions/dependency-check@v7
        with:
          # Название проекта (показывается в отчёте)
          project-name: "Python Project"

          # Уровень CVSS, при котором действие завершится с ошибкой
          # 0 = не падать, 7 = высокая уязвимость (HIGH/Critical), 4 = средний и выше
          fail-on-cvss: 7

          # Форматы отчётов
          format: "HTML"

          # Путь, куда сохранить отчёт
          out: "dependency-check-report"

          # Опционально: API-ключ для Sonatype OSS Index (если есть)
          # Ускоряет проверку и даёт доступ к дополнительным данным
          # Добавь секрет OWASP_API_KEY в Settings → Secrets → Actions
          # ossindex.enabled: true
          # ossindex.username: "unused"
          # ossindex.token: ${{ secrets.OWASP_API_KEY }}

      - name: Upload report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: owasp-dependency-check-report
          path: dependency-check-report/
