name: OWASP Dependency-Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Download OWASP Dependency-Check
        run: |
          wget https://github.com/jeremylong/DependencyCheck/releases/download/v9.0.9/dependency-check-9.0.9-release.zip
          unzip dependency-check-9.0.9-release.zip

      - name: Verify API key access
        run: |
          curl -H "Accept: application/json" -H "apiKey: ${{ secrets.NVD_API_KEY }}" \
            -v "https://services.nvd.nist.gov/rest/json/cves/2.0?cpeName=cpe:2.3:o:microsoft:windows_10:1607:*:*:*:*:*:*:*" \
            -o /dev/null -w "%{http_code}"

      - name: Run Dependency-Check with verified key
        run: |
          ./dependency-check/bin/dependency-check.sh \
            --scan . \
            --format HTML \
            --project "Python-GitHub-Action" \
            --out . \
            --nvdApiKey ${{ secrets.NVD_API_KEY }} \
            --nvdApiDelay 6000 \
            --nvdMaxRetryCount 10 \
            --connectionTimeout 30000 \
            --readTimeout 120000