name: Dependency Check with Cached Database

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'  # Run weekly

jobs:
  dependency-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Cache vulnerability database
      id: cache-db
      uses: actions/cache@v4
      with:
        path: ./.dependency-check-data
        key: ${{ runner.os }}-dependency-check-db-${{ github.run_id }}
        restore-keys: |
          ${{ runner.os }}-dependency-check-db-
      
    - name: Ensure cache directory exists
      run: mkdir -p ./.dependency-check-data
      
    - name: Run Dependency-Check with Docker
      run: |
        mkdir -p reports
        
        docker run --rm \
          -v $(pwd):/src \
          -v $(pwd)/.dependency-check-data:/usr/share/dependency-check/data \
          -v $(pwd)/reports:/report \
          owasp/dependency-check:latest \
          --scan /src \
          --format "HTML" \
          --format "XML" \
          --project "My Python Project" \
          --out /report \
          --enableExperimental
      
    - name: Upload Dependency-Check reports
      uses: actions/upload-artifact@v4
      with:
        name: dependency-check-reports
        path: reports/
        
    - name: Check for high severity issues
      run: |
        if grep -q "CVSS score >= 8.0" reports/dependency-check-report.html; then
          echo "High severity vulnerabilities found!"
          exit 1
        fi
