name: OWASP Dependency-Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  dependency-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          
      - name: Cache dependency-check data
        uses: actions/cache@v3
        with:
          path: ~/.dependency-check
          key: ${{ runner.os }}-dependency-check-${{ hashFiles('**/pom.xml', '**/build.gradle', '**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-dependency-check-
      
      - name: Run Dependency-Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: 'My Project'
          path: '.'
          format: 'HTML'
          out: 'reports'
          args: >
            --enableExperimental
            --suppression suppression.xml
          
      - name: Upload report
        uses: actions/upload-artifact@v3
        with:
          name: dependency-check-report
          path: reports/dependency-check-report.html
          
      - name: Check for vulnerabilities
        run: |
          if grep -q "<td>High</td>" reports/dependency-check-report.html || grep -q "<td>Critical</td>" reports/dependency-check-report.html; then
            echo "High or Critical vulnerabilities found!"
            exit 1
          fi
