name: OWASP Dependency Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  dependency-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          
      - name: OWASP Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: 'Your-Project-Name'
          path: '.'
          format: 'HTML'
          out: 'reports'
          args: >
            --scan .
            --suppression ./suppression.xml
            --failOnCVSS 7
            --enableExperimental
            
      - name: Upload Test results
        uses: actions/upload-artifact@v3
        with:
          name: Dependency Check Report
          path: ${{ github.workspace }}/reports
          
      - name: Upload sarif report to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: ${{ github.workspace }}/reports/dependency-check-report.sarif
